apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - api-gateway/app.yaml
  - user-service/app.yaml
  - product-service/app.yaml
  - order-service/app.yaml
  - payment-service/app.yaml
  - notification-service/app.yaml