apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: notification-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/KubeNexa/GitOps.git
    targetRevision: main
    path: base/notificationservice
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true